name: generate changelog and create release

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'CHANGELOG.md'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@8118086024a5380b05b0d54ed2181516082e090f # v4
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'

      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
