name: CLI testing

on:
  pull_request:
    branches: ['main']

jobs:
  bats_tests:
    runs-on: ubuntu-latest
    name: Run Bats Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Bats suite
        uses: bats-core/bats-action@v3.0.1
        with:
          test-path: tests/unit
