name: Pulumi Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry install --with dev --no-root --no-interaction

      - name: Run unit suite
        run: make test-unit
