name: Pulumi Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test container
        run: docker compose build pulumi

      - name: Run unit suite
        run: make test-unit
